# ──── Prefix ──────────────────────────────────────────────────────────────────────────────────
unbind C-b
set-option -g prefix C-S-Space
bind C-S-a send-prefix


# ──── Colors ──────────────────────────────────────────────────────────────────────────────────
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:Ms=\E]12;%p1%s\007'


# ──── Mouse ───────────────────────────────────────────────────────────────────────────────────
set -g mouse on


# ──── History ─────────────────────────────────────────────────────────────────────────────────
set -g history-limit 50000
set -g history-file ~/.tmux_history
